for(var i=0;i<document.getElementsByClassName("photo").length;i++){
    if(i==0)
    {
        document.getElementsByClassName("photo")[i].onclick=function(){
            document.getElementById("idStr").style.display="block";
        };
    }
    if(i==2)
    {
        document.getElementsByClassName("photo")[i].onclick=function(){
            document.getElementById("idTriggers").style.display="block";
        };
    }
    if(i==4)
    {
        document.getElementsByClassName("photo")[i].onclick=function(){
            document.getElementById("idViews").style.display="block";
        };
    }
    if(i==6)
    {
        document.getElementsByClassName("photo")[i].onclick=function(){
            document.getElementById("idInsData").style.display="block";
        };
    }
    if(i==3)
    {
        document.getElementsByClassName("photo")[i].onclick=function(){
            document.getElementById("idFrgK").style.display="block";
        };
    }
    if(i==1)
    {
        document.getElementsByClassName("photo")[i].onclick=function(){
            document.getElementById("idIndx").style.display="block";
        };
    }
    if(i==5)
    {
        document.getElementsByClassName("photo")[i].onclick=function(){
            document.getElementById("idSelDat").style.display="block";
        };
    }
    if(i==7)
    {
        document.getElementsByClassName("photo")[i].onclick=function(){
            document.getElementById("idAddN").style.display="block";
        };
    }

}
